# Configuration file for PlayerSize by Rushil13579

# Use '&' for color

# Set this to true to enable FormAPI support, and false to disable. [Set to true only if FormAPI is installed]
playersize-formapi-support: false

# Set this to true to enable a permission for playersize commands
playersize-permission-enabled: true

# Permission for the playersize commands [Only matters if playersize-permission-enabled is set to true]
playersize-permission: "playersize.use"

# Title of the playersize form [Only matters if playersize-formapi-support is true]
playersize-form-title: "&3[&bPlayerSize&3]"

# Worlds in which PlayerSize commands wont work
blacklisted-worlds:
  - world1
  - world2
