# Configuration file for PlayerSize by Rushil13579

# Use '&' for color

# Set this to true to enable FormAPI support, and false to disable. [Set to true only if FormAPI is installed]
playersize-formapi-support: false

# Set this to true to enable a permission for playersize commands
playersize-permission-enabled: true

# Permission for the playersize commands [Only matters if playersize-permission-enabled is set to true]
playersize-permission: "playersize.use"

# EVERYTHING UNDER THIS ONLY MATTERS IF playersize-formapi-support is true

# Title of the playersize form
playersize-form-title: "&3[&bPlayerSize&3]"

# Name of the playersize form normal button
playersize-form-normal-button: "&aShow"

# Name of the playersize form small button
playersize-form-small-button: "&dSmall"

# Name of the playersize form hide button
playersize-form-hide-button: "&7Hide"
